### 제너레이터 

In [14]:
def foo():
    print("step.1")
    yield 1

In [15]:
a = foo()

In [16]:
a

<generator object foo at 0x000001E7382C5E40>

In [17]:
next(a)  ## a.__next__()

step.1


1

In [18]:
next(a)

StopIteration: 

In [19]:
for i in foo():
    print(i)

step.1
1


In [20]:
def foo():
    yield 1
    yield 2

In [21]:
for i in foo():
    print(i)

1
2


In [24]:
def foo():
    for i in range(3):
        yield i+1

In [25]:
for i in foo():
    print(i)

1
2
3


In [27]:
def my_range(stop):
    x = 0
    while x < stop:
        yield x
        x += 1

In [28]:
for i in my_range(3):
    print(i)

0
1
2


In [29]:
for i in range(1, 3):
    print(i)

1
2


In [30]:
def my_range(start, stop):
    x = start 
    while x < stop:
        yield x
        x += 1

In [31]:
for i in my_range(1, 3):
    print(i)

1
2


In [32]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [33]:
def my_range(start, stop, step):
    x = start 
    while x < stop:
        yield x
        x += step

In [34]:
for i in my_range(1, 10, 2):
    print(i)

1
3
5
7
9


### 코루틴

In [42]:
def foo():
    n = yield
    print(n)

In [43]:
a = foo()

In [44]:
next(a)

In [45]:
a.send(1)

1


StopIteration: 

### 넘파이(numpy)

In [48]:
import numpy 

numpy.array([1,2,3])

array([1, 2, 3])

In [57]:
import numpy as np

a1 = np.array([1,2,3])
print(a1)
print(len(a1))
print(a1.ndim)
print(a1.shape)

l1 = [1,2,3]
print(l1)
print(len(l1))
# print(l1.ndim)
# print(l1.shape)

[1 2 3]
3
1
(3,)
[1, 2, 3]
3


In [59]:
import numpy as np

a1 = np.array([[1,2],[3,4]])
print(a1)
print(len(a1))
print(a1.ndim)
print(a1.shape)

[[1 2]
 [3 4]]
2
2
(2, 2)


In [60]:
import numpy as np

a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
print(len(a1))
print(a1.ndim)
print(a1.shape)

[[1 2]
 [3 4]
 [5 6]]
3
2
(3, 2)


In [61]:
import numpy as np

a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
print(len(a1))
print(a1.ndim)
print(a1.shape)

[[1 2 3]
 [4 5 6]]
2
2
(2, 3)


### 배열 초기화 문법

In [62]:
import numpy as np

a1 = np.array([[1,2,3],[4,5,6]])

In [63]:
print(a1)

[[1 2 3]
 [4 5 6]]


In [64]:
a1 = np.array([[0,0,0],[0,0,0]])
a1

array([[0, 0, 0],
       [0, 0, 0]])

In [67]:
a1 = np.zeros((2,3))
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [68]:
a1 = np.ones((2,3))
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [69]:
a1 = np.full((2,3),7)
print(a1)

[[7 7 7]
 [7 7 7]]


In [70]:
a1 = np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 형상 변환( reshape )

In [79]:
a1 = np.array(range(12))
a2 = a1.reshape((3,4))
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a1 = np.array(range(12)).reshape((3,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a1 = np.array(range(12)).reshape((4,3))
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
a2=a1.reshape((12,))
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### numpy 슬라이싱

In [94]:
a1 = np.array(range(12))
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
a1[4]

4

In [96]:
a1[0:6]

array([0, 1, 2, 3, 4, 5])

In [99]:
a1[:6]

array([0, 1, 2, 3, 4, 5])

In [100]:
a1[-1]

11

In [101]:
a2=a1.reshape((4,3))
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
a2[1]

array([3, 4, 5])

In [104]:
a2[1][1]

4

In [105]:
a2[1, 1]

4

In [107]:
a3 = a2[0:2, 0:2]
a3

array([[0, 1],
       [3, 4]])

In [109]:
a4 = a2[1:, 1:]
a4

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [110]:
a5 = a2[0:2, 1]
a5

array([1, 4])

### 정수 인덱싱

In [111]:
a6 = a2[[0,2], :]
a6

array([[0, 1, 2],
       [6, 7, 8]])

In [112]:
a7 = a2[[0,2], [1,2]]
a7

array([1, 8])

In [113]:
a = [0,3]
a8 = a2[a, 2]
a8

array([ 2, 11])

### 부울린 인덱싱

In [114]:
lst =  [[1,2,3],
        [4,5,6],
        [7,8,9]]

a1 = np.array(lst)

In [117]:
b1 = np.array([[True,False,True],
               [False,True,False],
               [True,False,True]])
print(a1[b1])

[1 3 5 7 9]


In [119]:
print(a1[ a1%2 != 0 ])

[1 3 5 7 9]


### numpy의 연산

In [120]:
a = [1,2,3]
b = [4,5,6]
c = a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [122]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b # 멤버별로 더하기 됨
print(c)

[5 7 9]


In [123]:
c = a-b # 멤버별로 빼기 됨
print(c)

[-3 -3 -3]


In [124]:
c = a*b # 멤버별로 곱하기 됨
print(c)

[ 4 10 18]


In [125]:
c = a/b # 멤버별로 나누기 됨
print(c)

[0.25 0.4  0.5 ]


In [126]:
c = a%b # 멤버별로 나머지 연산 됨
print(c)

[1 2 3]


### 브로드 캐스팅

In [127]:
a = np.array([1,2,3])
b = 10
c = a+b # 모든 멤버에 10이 더해진다.
print(c)

[11 12 13]
